### ISSUE TITLE
fs.Unlink -- Promise -- Directory Test

### ISSUE THREAD

**Issue by mphan6** [filerjs/filer#444] opened 2018-09-22 17:15 UTC
Hello,
There isn't a promise version of a ```fs.Unlink()``` -- ``` √ should not unlink directories``` .
I'd like to be assigned this issue and create the test.

**Comment by dnguneratne** [comment] 2018-09-24 02:56
Dupe of #431

**Closed** 2018-12-13 02:02 UTC
